version: "2"
run:
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: disable

linters:
  settings:
    errcheck:
      check-blank: false
      exclude-functions:
        - fmt:.*
    nolintlint:
      require-specific: true
  exclusions:
    paths:
      - demos
      - ".*_test.go"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
