run:
  deadline: 5m
  skip-dirs:
    - demos
  skip-files:
    - ".*_test.go"
linters:
  enable-all: true
  disable:
    - varnamelen
    - exhaustruct
    # deprecated
    - rowserrcheck
    - wastedassign
    - structcheck
    - deadcode
    - varcheck
    - nosnakecase
    - ifshort
    - golint
    - maligned
    - interfacer
    - scopelint
    - exhaustivestruct
linters-settings:
  errcheck:
    check-blank: false
    ignore: fmt:.*
  nolintlint:
    require-specific: true
